guildID: "1040756957931384873"

###################
#     Booleans    #
###################

ban: 
  enabled: true
mute:
  enabled: true
unmute:
  enabled: true
kick:
  enabled: true
nuke:
  enabled: true
tempban:
  enabled: true
unban:
  enabled: true
history:
  enabled: true
dick:
  enabled: true
iq:
  enabled: true
say:
  enabled: true
troll:
  enabled: true
  max_mentions: 10
  message: "You cant mention that amount! The max is {max_mentions}"
dm:
  enabled: true
ping:
  enabled: true
tempmute:
  enabled: true

###################
#      Roles      #
###################

roles:
  staff: "1086412212224147578"
  muted: "1086408463267143701"


###################
#     Channels    #
###################

channels:
  logs: "1086796908967764048"
  suggestions: "1086797308194201680"
  welcome: "1086810290127130715"
  
###################
#     Embeds      #
###################

disabled:
  title: "⚠️ Warning Notice ⚠️"
  description: "> This command is disabled please enable it on the config!\n *This embed will be deleted in 3 seconds.*"
  color: "Yellow"
user_has_roles:
  title: "⚠️ Warning Notice ⚠️"
  description: "> The user you are trying to give a role to/mute already has that role!\n *This embed will be deleted in 5 seconds.*"
  color: "Yellow"