ban:
  title: "Ban has been successfully issued."
  description: "> {user} has been banned from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
unban:
  title: "Ban has been successfully removed."
  description: "> {user} has been unbanned from the server.\n\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Green"
mute:
  role: "1086408463267143701"
  title: "Mute has been successfully issued."
  description: "> {user} has been muted from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
unmute:
  title: "Mute has been successfully removed."
  description: "> {user} has been unmuted from the server.\n\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Green"
kick:
  title: "Kick has been successfully issued."
  description: "> {user} has been kicked from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
history: 
  title: "User history"
  description: "> {user}"
  color: "Red"
nuke: 
  title: "Channel has been successfully nuked."
  description: "> *{channel}* has been nuked.\n\n> **Nuked by:** {username}\n> **Date:** {date}"
  color: "Red"
serverinfo:
  title: "{servername}"
  description: "> **Owner:**\n> <@{serverowner}>\n> **Created At:** > \n{servercreateddate}\n> **Member Count:** > \n{membercount}"
  color: "Orange"
messageupdate:
  title: "Message has been updated."
  description: "> Message sent by {oldMessageAuthor} in {oldMessageChannel}"
  fields:
    one:
      name: "Old Message"
      value: "> {oldMessageContent}"
    two:
      name: "New Message"
      value: "> {newMessageContent}"
  color: "Orange"