ban:
  title: "Ban has been successfully issued."
  description: "> {user} has been banned from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
unban:
  title: "Ban has been successfully removed."
  description: "> {user} has been unbanned from the server.\n\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Green"
mute:
  title: "Mute has been successfully issued."
  description: "> {user} has been muted from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
  tempmute:
    title: "Mute has been successfully issued."
    description: "> {user} has been muted from the server.\n\n> **Reason:** {reason}\n> **Time:** {time_muted} \n> **Moderator:** {moderator}\n> **Date:** {date}"
    color: "Red"
    fields:
      one:
        name: "User"
        value: "> {user}"
      two:
        name: "Reason"
        value: "> {Reason}"
      three:
        name: "Time"
        value: "> {time}"
      four:
        name: "Moderator"
        value: "> {moderator}"
      five:
        name: "Date"
        value: "> {date}"
unmute:
  title: "Mute has been successfully removed."
  description: "> {user} has been unmuted from the server.\n\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Green"
kick:
  title: "Kick has been successfully issued."
  description: "> {user} has been kicked from the server.\n\n> **Reason:** {reason}\n> **Moderator:** {moderator}\n> **Date:** {date}"
  color: "Red"
history: 
  bans:
    title: "{user}'s ban sanctions"
    fields:
      one: 
        name: "Staff"
        value: "{staff}"
      two:
        name: "Reason"
        value: "{reason}"
      three:
        name: "Date"
        value: "{date}"
    color: "Orange"
  mute:
    title: "{user}'s mute sanctions"
    fields:
      one: 
        name: "Staff"
        value: "{staff}"
      two:
        name: "Reason"
        value: "{reason}"
      three:
        name: "Date"
        value: "{date}"
    color: "Orange"
  nohistory:
    title: "No sanctions found for {user}."
    description: "> If you think this is an error, please contact a staff member."
    color: "Orange"
nuke: 
  title: "Channel has been successfully nuked."
  description: "> *{channel}* has been nuked.\n\n> **Nuked by:** {username}\n> **Date:** {date}"
  color: "Red"
serverinfo:
  title: "{servername}"
  description: "> **Owner:**\n> <@{serverowner}>\n> **Created At:** > \n{servercreateddate}\n> **Member Count:** > \n{membercount}"
  color: "Orange"
dick:
  description: "You dick size is {dicksize}cm"
  color: "Orange"
iq:
  description: "Your IQ is {iq}"
  color: "Orange"
troll:
  max_mentions: 10
  number_exceeded: "You can only mention {max_mentions} users at a time."
role:
  title: "Role has been successfully issued."
  description: "> {user} has been given the role <@&{role}>."
  color: "Orange"
tempmute:

########################
#     Logs Embeds      #
########################

message:
  updated:
    title: "Message has been updated."
    description: "> Message sent by {oldMessageAuthor} in {oldMessageChannel}"
    fields:
      one:
        name: "Old Message"
        value: "> {oldMessageContent}"
      two:
        name: "New Message"
        value: "> {newMessageContent}"
    color: "Orange"
  deleted:
    title: "Message has been deleted."
    description: "> Message sent by {author} in {channel}"
    fields:
      one:
        name: "Message"
        value: "> {deleted_message}"
    color: "Orange"
voice:
  join:
    title: "Member Joined Voice Channel"
    description: "**Channel**\n> <#{channel}>\n\n**User**\n> <@{user}>\n\n**Date**\n> {time}"
    color: "Green"
  leave:
    title: "Member Left Voice Channel"
    description: "**Channel**\n> <#{channel}>\n\n**User**\n> <@{user}>\n\n**Date**\n> {time}"
    color: "Red"